FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --frozen-lockfile

COPY . .

ENV NX_DAEMON=false

RUN npx nx sync
RUN npx nx build @org/ai-service

EXPOSE 3009

CMD ["node", "apps/ai-service/dist/main.js"]