FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --frozen-lockfile

COPY . .

ENV NX_DAEMON=false

RUN npx nx build @org/gateway-service

EXPOSE 3006

CMD ["node", "apps/gateway-service/dist/main.js"]
