FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/gateway-service/package.json ./apps/gateway-service/

RUN npm ci

COPY . .

ENV NX_DAEMON=false

RUN npx nx sync
RUN npx nx build @org/gateway-service

EXPOSE 3006

CMD ["node", "apps/gateway-service/dist/main.js"]