FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --legacy-peer-deps

COPY . .

ENV NX_DAEMON=false

RUN npx prisma generate --config prisma.reservation.config.ts
RUN npx nx sync
RUN npx nx build @org/reservation-service

EXPOSE 3005

CMD ["node", "apps/reservation-service/dist/main.js"]
