FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/notification-service/package.json ./apps/notification-service/

RUN npm install

COPY . .

ENV NX_DAEMON=false

RUN npx nx sync
RUN npx nx build notification-service

EXPOSE 3011

CMD ["node", "apps/notification-service/dist/main.js"]