FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --frozen-lockfile

COPY . .

ENV NX_DAEMON=false

RUN npx prisma generate --config prisma.payment.config.ts
RUN npx nx build payment-service

EXPOSE 3007

CMD ["sh", "-c", "npx prisma db push --config prisma.payment.config.ts --accept-data-loss && node apps/payment-service/dist/main.js"]