FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --legacy-peer-deps

COPY . .

ENV NX_DAEMON=false

RUN npx prisma generate --config prisma.payment.config.ts
RUN npx nx sync
RUN npx nx build payment-service

EXPOSE 3007

CMD ["node", "apps/payment-service/dist/main.js"]