FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma

RUN npm install
COPY . .

RUN npx prisma generate --schema prisma/user/schema.prisma
RUN npx nx build @org/user-service

EXPOSE 3001
CMD ["sh", "-c", "npx prisma migrate deploy --schema prisma/user/schema.prisma && node apps/user-service/dist/main.js"]
