FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --legacy-peer-deps

COPY . .

ENV NX_DAEMON=false

RUN npx prisma generate --config prisma.user.config.ts
RUN npx nx sync
RUN npx nx build @org/user-service

EXPOSE 3001

CMD ["node", "apps/user-service/dist/main.js"]
