FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --frozen-lockfile

COPY . .

ENV NX_DAEMON=false

RUN npx prisma generate --config prisma.user.config.ts
RUN npx nx build @org/user-service

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy --config prisma.user.config.ts && node apps/user-service/dist/main.js"]
