FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --legacy-peer-deps

COPY . .

ENV NX_DAEMON=false

RUN npx prisma generate --config prisma.parking.config.ts
RUN npx nx sync
RUN npx nx build @org/parking-service

EXPOSE 3004

CMD ["node", "apps/parking-service/dist/main.js"]
