FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --frozen-lockfile

COPY . .

ENV NX_DAEMON=false

RUN npx prisma generate
RUN npx nx sync
RUN npx nx build @org/auth-service

EXPOSE 3000

CMD ["node", "apps/auth-service/dist/main.js"]
