name: CI

on:
  push:
    branches: [main, QA, qa, PROD, prod, develop]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: smart-parking/package-lock.json

      - run: npm ci --prefix smart-parking

      - name: Lint
        run: cd smart-parking && npx nx run-many --target=lint --all --parallel=3

      - name: Unit Tests
        run: cd smart-parking && npx nx run-many --target=test --all --parallel=3 --ci --coverage

      - name: Build
        run: cd smart-parking && npx nx run-many --target=build --all --parallel=3