name: CI

on:
  workflow_call:
  push:
    branches: [main, QA, qa, PROD, prod, develop]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: smart-parking/package-lock.json

      - run: npm ci --prefix smart-parking

      - name: Lint auth
        run: cd smart-parking && npx nx run @org/auth-service:lint --verbose

      - name: Unit Tests
        run: cd smart-parking && npx nx run-many --target=test --all --parallel=3 --ci --coverage

      - name: Build Backend
        run: cd smart-parking && npx nx run-many --target=build --all --exclude=frontend --parallel=3

      - name: Build
        env:
          NEXT_PUBLIC_AUTH_API_URL: http://localhost:3000/api
          NEXT_PUBLIC_USER_API_URL: http://localhost:3001/api
          NEXT_PUBLIC_VEHICLE_API_URL: http://localhost:3003/api
          NEXT_PUBLIC_PARKING_API_URL: http://localhost:3004/api
          NEXT_PUBLIC_RESERVATION_API_URL: http://localhost:3005/api
        run: cd smart-parking && npx nx run-many --target=build --all --parallel=3